/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LRouteImport } from './routes/l'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteInvitationIdRouteImport } from './routes/invite.$invitationId'
import { Route as ASlugRouteImport } from './routes/a.$slug'
import { Route as RawSessionTokenRouteImport } from './routes/raw.session.$token'
import { Route as ApiV1SplatRouteImport } from './routes/api.v1.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ASlugVersionRouteImport } from './routes/a.$slug.$version'
import { Route as RawAArtifactIdVersionIdSplatRouteImport } from './routes/raw.a.$artifactId.$versionId.$'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LRoute = LRouteImport.update({
  id: '/l',
  path: '/l',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInvitationIdRoute = InviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ASlugRoute = ASlugRouteImport.update({
  id: '/a/$slug',
  path: '/a/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RawSessionTokenRoute = RawSessionTokenRouteImport.update({
  id: '/raw/session/$token',
  path: '/raw/session/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ASlugVersionRoute = ASlugVersionRouteImport.update({
  id: '/$version',
  path: '/$version',
  getParentRoute: () => ASlugRoute,
} as any)
const RawAArtifactIdVersionIdSplatRoute =
  RawAArtifactIdVersionIdSplatRouteImport.update({
    id: '/raw/a/$artifactId/$versionId/$',
    path: '/raw/a/$artifactId/$versionId/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/device': typeof DeviceRoute
  '/l': typeof LRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/a/$slug': typeof ASlugRouteWithChildren
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/a/$slug/$version': typeof ASlugVersionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/raw/session/$token': typeof RawSessionTokenRoute
  '/raw/a/$artifactId/$versionId/$': typeof RawAArtifactIdVersionIdSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/device': typeof DeviceRoute
  '/l': typeof LRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/a/$slug': typeof ASlugRouteWithChildren
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/a/$slug/$version': typeof ASlugVersionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/raw/session/$token': typeof RawSessionTokenRoute
  '/raw/a/$artifactId/$versionId/$': typeof RawAArtifactIdVersionIdSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/device': typeof DeviceRoute
  '/l': typeof LRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/a/$slug': typeof ASlugRouteWithChildren
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/a/$slug/$version': typeof ASlugVersionRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/raw/session/$token': typeof RawSessionTokenRoute
  '/raw/a/$artifactId/$versionId/$': typeof RawAArtifactIdVersionIdSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts'
    | '/device'
    | '/l'
    | '/login'
    | '/settings'
    | '/a/$slug'
    | '/invite/$invitationId'
    | '/a/$slug/$version'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/raw/session/$token'
    | '/raw/a/$artifactId/$versionId/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artifacts'
    | '/device'
    | '/l'
    | '/login'
    | '/settings'
    | '/a/$slug'
    | '/invite/$invitationId'
    | '/a/$slug/$version'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/raw/session/$token'
    | '/raw/a/$artifactId/$versionId/$'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/device'
    | '/l'
    | '/login'
    | '/settings'
    | '/a/$slug'
    | '/invite/$invitationId'
    | '/a/$slug/$version'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/raw/session/$token'
    | '/raw/a/$artifactId/$versionId/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRoute
  DeviceRoute: typeof DeviceRoute
  LRoute: typeof LRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  ASlugRoute: typeof ASlugRouteWithChildren
  InviteInvitationIdRoute: typeof InviteInvitationIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  RawSessionTokenRoute: typeof RawSessionTokenRoute
  RawAArtifactIdVersionIdSplatRoute: typeof RawAArtifactIdVersionIdSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l': {
      id: '/l'
      path: '/l'
      fullPath: '/l'
      preLoaderRoute: typeof LRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$invitationId': {
      id: '/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$slug': {
      id: '/a/$slug'
      path: '/a/$slug'
      fullPath: '/a/$slug'
      preLoaderRoute: typeof ASlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw/session/$token': {
      id: '/raw/session/$token'
      path: '/raw/session/$token'
      fullPath: '/raw/session/$token'
      preLoaderRoute: typeof RawSessionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$slug/$version': {
      id: '/a/$slug/$version'
      path: '/$version'
      fullPath: '/a/$slug/$version'
      preLoaderRoute: typeof ASlugVersionRouteImport
      parentRoute: typeof ASlugRoute
    }
    '/raw/a/$artifactId/$versionId/$': {
      id: '/raw/a/$artifactId/$versionId/$'
      path: '/raw/a/$artifactId/$versionId/$'
      fullPath: '/raw/a/$artifactId/$versionId/$'
      preLoaderRoute: typeof RawAArtifactIdVersionIdSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ASlugRouteChildren {
  ASlugVersionRoute: typeof ASlugVersionRoute
}

const ASlugRouteChildren: ASlugRouteChildren = {
  ASlugVersionRoute: ASlugVersionRoute,
}

const ASlugRouteWithChildren = ASlugRoute._addFileChildren(ASlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRoute,
  DeviceRoute: DeviceRoute,
  LRoute: LRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  ASlugRoute: ASlugRouteWithChildren,
  InviteInvitationIdRoute: InviteInvitationIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  RawSessionTokenRoute: RawSessionTokenRoute,
  RawAArtifactIdVersionIdSplatRoute: RawAArtifactIdVersionIdSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
